const clientsTypes = {
  DATA_INITIALIZED: 'DATA_INITIALIZED',

  SELECT_CLIENT: 'SELECT_CLIENT',
  SELECT_SUCCESS: 'SELECT_SUCCESS',
  SELECT_FAIL: 'SELECT_FAIL',

  UPDATE_RESOLVE: 'UPDATE_RESOLVE',
  UPDATE_RESOLVE_SUCCSSS: 'UPDATE_RESOLVE_SUCCSSS',
  UPDATE_RESOLVE_FAIL: 'UPDATE_RESOLVE_FAIL',

  UPDATE_NAME: 'UPDATE_NAME',
  UPDATE_NAME_SUCCSSS: 'UPDATE_NAME_SUCCSSS',
  UPDATE_NAME_FAIL: 'UPDATE_NAME_FAIL',

  UPDATE_PHONE: 'UPDATE_PHONE',
  UPDATE_PHONE_SUCCSSS: 'UPDATE_PHONE_SUCCSSS',
  UPDATE_PHONE_FAIL: 'UPDATE_PHONE_FAIL',

  CREATE_CLIENT: 'CREATE_CLIENT',
  CREATE_CLIENT_SUCCESS: 'CREATE_CLIENT_SUCCESS',
  CREATE_CLIENT_FAIL: 'CREATE_CLIENT_FAIL',

  TRASH_CLIENT: 'TRASH_CLIENT',

  DELETE_CLIENT: 'DELETE_CLIENT',
  DELETE_CLIENT_SUCCESS: 'DELETE_CLIENT_SUCCESS:',
  DELETE_CLIENT_FAIL: 'DELETE_CLIENT_FAIL',

  SEND_MESSAGE: 'SEND_MESSAGE',
  NEW_MESSAGE: 'NEW_MESSAGE',

  RECEIVE: 'redux/message/RECEIVE',
  RECEIVE_SUCCESS: 'redux/message/RECEIVE_SUCCESS',
  RECEIVE_FAIL: 'redux/message/RECEIVE_FAIL',

  ADD_NOTE: 'ADD_NOTE',
  DELETE_NOTE: 'DELETE_NOTE',
  DELETE_CLIENT_BY_ID: 'DELETE_CLIENT_BY_ID',
  DRAG_NOTE: 'DRAG_NOTE',

  CHANGE_LABEL: 'CHANGE_LABEL',

  RECEIVE_CREATE_CLIENT: 'RECEIVE_CREATE_CLIENT',
  RECEIVE_CREATE_CLIENT_SUCCESS: 'RECEIVE_CREATE_CLIENT_SUCCESS',
  RECEIVE_CREATE_CLIENT_FAIL: 'RECEIVE_CREATE_CLIENT_FAIL',

  NEW_CLIENT_AND_MESSAGE: 'NEW_CLIENT_AND_MESSAGE',

  REDIRECT_FROM_USERS_TO_INBOX: 'REDIRECT_FROM_USERS_TO_INBOX',

  UPDATE_CLIENT_ORDERED_MAP: 'UPDATE_CLIENT_ORDERED_MAP',
};

export default clientsTypes;
